---
- hosts: localhost
  gather_facts: yes
  connection: local
  
  tasks:
  - name: Print facts
    command: 'echo Hostname is {{ ansible_hostname }}'
    register: result
  - debug: var=result
    
